### ISSUE TITLE
Update logo to new vector graphics

### ISSUE THREAD

**Issue by jerrettl** [Wiki-Knights/CS-Materials#50]
With the creation of the new branding and logo earlier this year, the logo has been updated to a new design. This new logo has been recreated using vector graphics as well. The logo needs to be updated in the favicon and the top of the page in the HTML template.

**Comment by panbed** [comment]
Oopsie, well actually, we just looked over it in the Discord and there seems to be an issue with the logo in certain tutorials (maybe if the title is too long?)
![image](https://github.com/wikiknights/cs-materials/assets/106042766/a11cd194-7abd-4ea7-889a-be563c3ce244)

**Comment by jerrettl** [comment]
All good now from #63 and #64. Whew!
